In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import scale
from sklearn import metrics
import pandas as pd
import yfinance as yf
import numpy as np
import matplotlib.pyplot as plt

In [4]:
start='2017-01-01'
end='2021-10-01'

In [5]:
data=yf.download('CL=F PTTEP.BK GPSC.BK PTTGC.BK PTT.BK',start=start,end=end)

[*********************100%***********************]  5 of 5 completed


In [6]:
data

Adj Close                                                   Close  \
                 CL=F    GPSC.BK     PTT.BK    PTTEP.BK   PTTGC.BK       CL=F   
Date                                                                            
2017-01-03  52.330002        NaN        NaN         NaN        NaN  52.330002   
2017-01-04  53.259998  29.146654  29.128017   74.474823  48.913532  53.259998   
2017-01-05  53.759998  28.555845  29.664589   74.096779  49.104595  53.759998   
2017-01-06  53.990002  28.555845  29.817898   74.474823  48.913532  53.990002   
2017-01-09  51.959999  28.555845  29.357981   73.907745  48.340328  51.959999   
...               ...        ...        ...         ...        ...        ...   
2021-09-24  73.980003        NaN        NaN         NaN        NaN  73.980003   
2021-09-27  75.449997  75.753326  37.146828  111.294357  58.820953  75.449997   
2021-09-28  75.290001  75.015472  37.146828  113.196823  60.726082  75.290001   
2021-09-29  74.830002  75.015472  37.099571  113.196823  60.249802  74.830002   
2021-09-30  75.029999  74.277611  36.863266  111.769974  60.249802  75.029999   

                                                    ...       Open             \
              GPSC.BK     PTT.BK PTTEP.BK PTTGC.BK  ...       CL=F    GPSC.BK   
Date                                                ...                         
2017-01-03        NaN        NaN      NaN      NaN  ...  54.200001        NaN   
2017-01-04  32.962139  38.000000    98.50    64.00  ...  52.490002  33.184856   
2017-01-05  32.293987  38.700001    98.00    64.25  ...  53.389999  33.184856   
2017-01-06  32.293987  38.900002    98.50    64.00  ...  53.730000  32.516705   
2017-01-09  32.293987  38.299999    97.75    63.25  ...  53.750000  32.516705   
...               ...        ...      ...      ...  ...        ...        ...   
2021-09-24        NaN        NaN      NaN      NaN  ...  73.239998        NaN   
2021-09-27  77.000000  40.500000   117.00    61.75  ...  74.190002  77.500000   
2021-09-28  76.250000  40.500000   119.00    63.75  ...  75.430000  77.000000   
2021-09-29  76.250000  39.250000   119.00    63.25  ...  74.379997  75.500000   
2021-09-30  75.500000  39.000000   117.50    63.25  ...  74.779999  76.250000   

                                           Volume                           \
               PTT.BK PTTEP.BK PTTGC.BK      CL=F     GPSC.BK       PTT.BK   
Date                                                                         
2017-01-03        NaN      NaN      NaN  727793.0         NaN          NaN   
2017-01-04  37.400002    96.25    63.25  512641.0   9234695.0   75879000.0   
2017-01-05  38.200001    98.50    64.25  517362.0   4532206.0   75282000.0   
2017-01-06  38.700001    98.00    64.50  528333.0   2796035.0   45129000.0   
2017-01-09  38.900002    98.50    64.00  564893.0   2037337.0   40455000.0   
...               ...      ...      ...       ...         ...          ...   
2021-09-24        NaN      NaN      NaN  350382.0         NaN          NaN   
2021-09-27  40.250000   115.00    60.50  417829.0   7722100.0  114666600.0   
2021-09-28  40.750000   118.50    62.50  476143.0   7964000.0  104953600.0   
2021-09-29  39.250000   117.00    63.25  424193.0   9205600.0   90070800.0   
2021-09-30  39.000000   119.00    63.25  583189.0  10934900.0   63650300.0   

                                    
              PTTEP.BK    PTTGC.BK  
Date                                
2017-01-03         NaN         NaN  
2017-01-04  17352200.0  14341900.0  
2017-01-05  18246200.0  12762900.0  
2017-01-06  11993700.0   8106700.0  
2017-01-09   4042300.0  10983300.0  
...                ...         ...  
2021-09-24         NaN         NaN  
2021-09-27  25185600.0  38175400.0  
2021-09-28  34817500.0  66383100.0  
2021-09-29  13055700.0  22502100.0  
2021-09-30  11996900.0  16324500.0  

[1231 rows x 30 columns]

In [7]:
df=data['Adj Close']

In [8]:
df

CL=F    GPSC.BK     PTT.BK    PTTEP.BK   PTTGC.BK
Date                                                              
2017-01-03  52.330002        NaN        NaN         NaN        NaN
2017-01-04  53.259998  29.146654  29.128017   74.474823  48.913532
2017-01-05  53.759998  28.555845  29.664589   74.096779  49.104595
2017-01-06  53.990002  28.555845  29.817898   74.474823  48.913532
2017-01-09  51.959999  28.555845  29.357981   73.907745  48.340328
...               ...        ...        ...         ...        ...
2021-09-24  73.980003        NaN        NaN         NaN        NaN
2021-09-27  75.449997  75.753326  37.146828  111.294357  58.820953
2021-09-28  75.290001  75.015472  37.146828  113.196823  60.726082
2021-09-29  74.830002  75.015472  37.099571  113.196823  60.249802
2021-09-30  75.029999  74.277611  36.863266  111.769974  60.249802

[1231 rows x 5 columns]

In [10]:
df =df.fillna(method='ffill').pct_change()

In [12]:
df=df.dropna()
df

CL=F   GPSC.BK    PTT.BK  PTTEP.BK  PTTGC.BK
Date                                                        
2017-01-05  0.009388 -0.020270  0.018421 -0.005076  0.003906
2017-01-06  0.004278  0.000000  0.005168  0.005102 -0.003891
2017-01-09 -0.037600  0.000000 -0.015424 -0.007614 -0.011719
2017-01-10 -0.021940  0.006896  0.013055 -0.017903  0.003953
2017-01-11  0.028139  0.006849 -0.007732  0.005209 -0.003937
...              ...       ...       ...       ...       ...
2021-09-24  0.009277  0.000000  0.000000  0.000000  0.000000
2021-09-27  0.019870 -0.012821  0.012500  0.035398  0.020661
2021-09-28 -0.002121 -0.009740  0.000000  0.017094  0.032389
2021-09-29 -0.006110  0.000000 -0.001272  0.000000 -0.007843
2021-09-30  0.002673 -0.009836 -0.006369 -0.012605  0.000000

[1229 rows x 5 columns]

In [18]:
df = df[['CL=F','GPSC.BK', 'PTTEP.BK' , 'PTTGC.BK' ,'PTT.BK']]
# re columns in dex put y value to last index

In [19]:
df

CL=F   GPSC.BK  PTTEP.BK  PTTGC.BK    PTT.BK
Date                                                        
2017-01-05  0.009388 -0.020270 -0.005076  0.003906  0.018421
2017-01-06  0.004278  0.000000  0.005102 -0.003891  0.005168
2017-01-09 -0.037600  0.000000 -0.007614 -0.011719 -0.015424
2017-01-10 -0.021940  0.006896 -0.017903  0.003953  0.013055
2017-01-11  0.028139  0.006849  0.005209 -0.003937 -0.007732
...              ...       ...       ...       ...       ...
2021-09-24  0.009277  0.000000  0.000000  0.000000  0.000000
2021-09-27  0.019870 -0.012821  0.035398  0.020661  0.012500
2021-09-28 -0.002121 -0.009740  0.017094  0.032389  0.000000
2021-09-29 -0.006110  0.000000  0.000000 -0.007843 -0.001272
2021-09-30  0.002673 -0.009836 -0.012605  0.000000 -0.006369

[1229 rows x 5 columns]

In [20]:
X=df.iloc[:,:-1] # without pttbk
y=df.iloc[:,-1] # only pttbk

In [21]:
X,y

(                CL=F   GPSC.BK  PTTEP.BK  PTTGC.BK
 Date                                              
 2017-01-05  0.009388 -0.020270 -0.005076  0.003906
 2017-01-06  0.004278  0.000000  0.005102 -0.003891
 2017-01-09 -0.037600  0.000000 -0.007614 -0.011719
 2017-01-10 -0.021940  0.006896 -0.017903  0.003953
 2017-01-11  0.028139  0.006849  0.005209 -0.003937
 ...              ...       ...       ...       ...
 2021-09-24  0.009277  0.000000  0.000000  0.000000
 2021-09-27  0.019870 -0.012821  0.035398  0.020661
 2021-09-28 -0.002121 -0.009740  0.017094  0.032389
 2021-09-29 -0.006110  0.000000  0.000000 -0.007843
 2021-09-30  0.002673 -0.009836 -0.012605  0.000000
 
 [1229 rows x 4 columns],
 Date
 2017-01-05    0.018421
 2017-01-06    0.005168
 2017-01-09   -0.015424
 2017-01-10    0.013055
 2017-01-11   -0.007732
                 ...   
 2021-09-24    0.000000
 2021-09-27    0.012500
 2021-09-28    0.000000
 2021-09-29   -0.001272
 2021-09-30   -0.006369
 Name: PTT.BK, Length: 122

In [24]:
from sklearn.model_selection import KFold

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=12)

In [30]:
X_train

CL=F   GPSC.BK  PTTEP.BK  PTTGC.BK
Date                                              
2017-05-22  0.007948  0.007353  0.005319  0.000000
2017-11-22  0.020940  0.008621  0.005391  0.003184
2021-08-12 -0.002311  0.000000  0.000000  0.000000
2017-01-18 -0.026677 -0.006897 -0.015625  0.019531
2019-07-15 -0.010463 -0.006993  0.000000  0.003984
...              ...       ...       ...       ...
2018-08-16  0.006922  0.025180 -0.010989 -0.009202
2018-11-01 -0.024805 -0.012987 -0.010753 -0.006472
2017-03-15  0.023889  0.040000 -0.008380 -0.013514
2018-02-01  0.016530 -0.009009  0.021008  0.000000
2018-09-05 -0.016459 -0.031142 -0.024561 -0.018692

[983 rows x 4 columns]

In [31]:
y_train

Date
2017-05-22    0.000000
2017-11-22    0.000000
2021-08-12    0.000000
2017-01-18   -0.005168
2019-07-15    0.000000
                ...   
2018-08-16   -0.009804
2018-11-01   -0.029412
2017-03-15   -0.005038
2018-02-01    0.012195
2018-09-05   -0.033493
Name: PTT.BK, Length: 983, dtype: float64

# exmaple Kfold random and result

In [26]:
kfold = KFold(10,shuffle=False,random_state=None)

In [28]:
for train,test  in kfold.split(y):
    print('train: %s, test: %s '% (y[train],y[test]))

train: Date
2017-06-28   -0.007895
2017-06-29   -0.005305
2017-06-30   -0.013333
2017-07-03    0.008108
2017-07-04    0.002681
                ...   
2021-09-24    0.000000
2021-09-27    0.012500
2021-09-28    0.000000
2021-09-29   -0.001272
2021-09-30   -0.006369
Name: PTT.BK, Length: 1106, dtype: float64, test: Date
2017-01-05    0.018421
2017-01-06    0.005168
2017-01-09   -0.015424
2017-01-10    0.013055
2017-01-11   -0.007732
                ...   
2017-06-21   -0.018229
2017-06-22    0.002653
2017-06-23    0.005291
2017-06-26   -0.002631
2017-06-27    0.002638
Name: PTT.BK, Length: 123, dtype: float64 
train: Date
2017-01-05    0.018421
2017-01-06    0.005168
2017-01-09   -0.015424
2017-01-10    0.013055
2017-01-11   -0.007732
                ...   
2021-09-24    0.000000
2021-09-27    0.012500
2021-09-28    0.000000
2021-09-29   -0.001272
2021-09-30   -0.006369
Name: PTT.BK, Length: 1106, dtype: float64, test: Date
2017-06-28   -0.007895
2017-06-29   -0.005305
2017-06-30   -0.01

In [32]:
from sklearn.model_selection import cross_val_score
reg= LinearRegression()
scores=cross_val_score(reg,X_train,y_train,scoring='r2',cv=5)
# cv is crossvalidation validator
# cv is K -> very large dataset use , K-3 , K-5 , normal K-10 
#if small use leave-oune-out cross -validation (LOOCV)
scores

array([0.5872626 , 0.48830486, 0.80354027, 0.69295388, 0.7397741 ])

In [34]:
from numpy import mean 
from numpy import std
print('Accuracy: %.2f SD: (%.2f)'% (mean(scores),std(scores)))

Accuracy: 0.66 SD: (0.11)


# we need conservative case for investment for worst case

In [36]:
kfold = KFold(3,shuffle=False,random_state=None)
reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='r2',cv=kfold)
scores

array([0.5501343 , 0.76876243, 0.72370448])

In [37]:
kfold = KFold(5,shuffle=False,random_state=None)
reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='r2',cv=kfold)
scores

array([0.5872626 , 0.48830486, 0.80354027, 0.69295388, 0.7397741 ])

In [44]:

reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='r2',cv=5)
scores
print('Accuracy: %.2f SD: (%.2f)'% (mean(scores),std(scores)))

Accuracy: 0.66 SD: (0.11)


In [43]:
# we will see error here  result is very have wide range
reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='r2',cv=10)
scores
print('Accuracy: %.2f SD: (%.2f)'% (mean(scores),std(scores)))

Accuracy: 0.64 SD: (0.14)


In [45]:

reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='r2',cv=3)
scores
print('Accuracy: %.2f SD: (%.2f)'% (mean(scores),std(scores)))

Accuracy: 0.68 SD: (0.09)


In [47]:

reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5)
scores


array([-1.03857742e-04, -1.23878493e-04, -1.05353114e-04, -8.68417223e-05,
       -1.05050651e-04])

In [48]:
# n jobs is use core to process njobs = 1 is use 1 core and -1 use all core
reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5
                        ,n_jobs=1,)
scores


array([-1.03857742e-04, -1.23878493e-04, -1.05353114e-04, -8.68417223e-05,
       -1.05050651e-04])

In [49]:
reg=LinearRegression()
scores = cross_val_score(reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5
                        ,n_jobs=-1,)
scores

array([-1.03857742e-04, -1.23878493e-04, -1.05353114e-04, -8.68417223e-05,
       -1.05050651e-04])